### ISSUE TITLE
建議: 可否增加 Always on Top 及 fullscreen mode 選項

### ISSUE THREAD

**Issue by kent79** [ExpTechTW/TREM-Lite-v2#10]
我是使用frontend開啓軟件的，但當打開時軟件便立即縮到最小。 

猜想可能軟件視窗沒有設定為Always on Top，可否增加此選項。

另外，預設打開軟件應該是windows mode，可否增加 fullscreen mode (視窗放到最大)選項。

這是一個很好的地震預測軟件，加油!

**Comment by whes1015** [comment]
不太清楚情況，請問有照片或影片嗎？

**Comment by kent79** [comment]
我用其他方法解決了，此post 可以close 了。謝謝!
