### ISSUE TITLE
目前無法連線伺服器資料[問題回報] 

### ISSUE THREAD

**Issue by snowolf50161** [ExpTechTW/TREM-Lite-v2#20]
### ✍🏻 描述詳細情況
* 預期效果:已連線地震資料
* 實際效果:未連線

### 📑 相關資訊
* 版本:1.10.10

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明:從昨天、下載之後就一直是離線的了
現在想看地震資料都沒辦法看

####  此檔案由 ExpTech.tw 設計製作
![Screenshot 2024-04-04 085534](https://github.com/ExpTechTW/TREM-Lite/assets/123584944/bd3752ac-4be6-40d9-838c-05475d5bac50)

**Comment by YacineBoussoufa** [comment]
Lite已停止維護 請改用其他分支版本
https://github.com/ExpTechTW/TREM-tauri
https://github.com/yayacat/TREM

**Comment by snowolf50161** [comment]
了解

Yacine Boussoufa ***@***.***>於 2024年4月4日 週四，上午10:40寫道：
