### ISSUE TITLE
 [問題回報] 無法連接到伺服器

### ISSUE THREAD

**Issue by dongdj631** [ExpTechTW/TREM-Lite-v2#21]
### ✍🏻 描述詳細情況
* 預期效果:提供地震報告
* 實際效果:為連接到伺服器

### 📑 相關資訊
* 版本:1.10.10

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明:下載完就不能用

####  此檔案由 ExpTech.tw 設計製作
![image](https://github.com/ExpTechTW/TREM-Lite/assets/153337401/b8c16fd5-4442-4450-99ed-4835d7bdf021)

**Comment by YacineBoussoufa** [comment]
https://github.com/ExpTechTW/TREM-tauri

**Comment by KevinYu0504** [comment]
+1 , same issue , no internet contact waring .

**Comment by YacineBoussoufa** [comment]
> +1 , same issue , no internet contact waring .

Use the link for TREM-tauri in the previous message

**Comment by KevinYu0504** [comment]
> > +1 , same issue , no internet contact waring .
> 
> Use the link for TREM-tauri in the previous message

Thanks , I had already try it an hours ago ,
however TREM-tauri also had many bugs ,
the report and setting page can't open  ....

So .. the TREM-lite version has no longer support(update) ? abandonware ?

I found an other TREM version by yayacat ,
Is this the version commonly used by everyone ?

**Comment by YacineBoussoufa** [comment]
I'm an user like you so I don't have all the info.
TREM-tauri is the newest version and it's still Work in Progress as it's in alpah stage and functionalities are reduced.
I think that TREM-lite has been abbandoned as it's no longer supported since like 6 months.

The version of yayacat is a valid alternative and I can confirm it's widely used by a lot of users.

**Comment by KevinYu0504** [comment]
> I'm an user like you so I don't have all the info. TREM-tauri is the newest version and it's still Work in Progress as it's in alpah stage and functionalities are reduced. I think that TREM-lite has been abbandoned as it's no longer supported since like 6 months.
> 
> The version of yayacat is a valid alternative and I can confirm it's widely used by a lot of users.

Many thanks !

Taiwan area had many earthquake in this few weeks ,
Just found this software on some YT stream ,
and the UI looks beautiful and the information seems easy and intuitive ,
so I would like to have a try .

TREM-tauri still buggy , lite version seems abandonware ,
the yayacat version I just try few min ago ,
still working , but too few setting details and functions .

anyway , thanks for your information , just found the official Discord page ,
I will keep attention on it . ;)
