### ISSUE TITLE
[問題回報] 伺服器斷線

### ISSUE THREAD

**Issue by Timyaya** [ExpTechTW/TREM-Lite-v2#42]
### ✍🏻 描述詳細情況
* 預期效果:
不會斷線

* 實際效果:
app 縮小畫面or掛後台會有斷線的情況

### 📑 相關資訊
* 版本:
2.0.0 pre.1

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明:

其他連結
Discord
https://discord.com/channels/926545182407688273/1253658099735334942

![image](https://github.com/ExpTechTW/TREM-Lite/assets/50204240/92a392e7-ebfa-4531-831a-4a44da575686)

![image](https://github.com/ExpTechTW/TREM-Lite/assets/50204240/9b225ec5-706b-4fb9-8912-5b7b7b59e4b2)

![image](https://github.com/ExpTechTW/TREM-Lite/assets/50204240/0b4d1842-fa20-4a2b-b7d6-4a2b02a96638)

**Comment by XingCh0405** [comment]
顯示畫面時也會出現斷線問題

**Comment by XingCh0405** [comment]
我剛又發現一件事 lite連線會斷斷續續的

**Comment by cstrikeasia** [comment]
ExpTechTW/API#136
