### ISSUE TITLE
建議：加入顏色對照條對應測站顏色的震度

### ISSUE THREAD

**Issue by joelin79** [ExpTechTW/TREM-Lite-v2#5]
### 🌟想法補充
* 補充說明:
像這種的（Jquake上的顏色條）
<img width="59" alt="image" src="https://github.com/ExpTechTW/TREM-Lite/assets/31405333/80415c7b-8dee-4911-90ec-4d4d62b86924">

**Comment by whes1015** [comment]
https://github.com/ExpTechTW/TREM-Lite/actions/runs/5843363940

**Comment by whes1015** [comment]
> ### 🌟想法補充
> * 補充說明:
>   像這種的（Jquake上的顏色條）
> 
> <img alt="image" width="59" src="https://user-images.githubusercontent.com/31405333/251616891-80415c7b-8dee-4911-90ec-4d4d62b86924.png"> #### 此檔案由 ExpTech.tw 設計製作

你有在 Discord群組 裡面嗎?

**Comment by joelin79** [comment]
沒有在discord群誒

**Comment by whes1015** [comment]
> 沒有在discord群誒

https://exptech.com.tw/f?v=discord
這是群組連結
