### ISSUE TITLE
建議: 可否加快捷鍵按下ESC將視窗縮到最小

### ISSUE THREAD

**Issue by kent79** [ExpTechTW/TREM-Lite-v2#8]
### 🌟想法補充
* 補充說明:

#### 此檔案由 ExpTech.tw 設計製作

如題，謝謝

**Comment by whes1015** [comment]
試試 1.9.7

**Comment by kent79** [comment]
先感謝了，正常快捷鍵ALT+F4可關程式，但不知為何不能，請也再檢查一下。

**Comment by kent79** [comment]
> 試試 1.9.7

已下載及測試了，十分感謝。 :)
